### ISSUE TITLE
About the Authorization Process

### ISSUE THREAD

**Issue by wyvrtn** [minisbett/osu-sharp-old#4]
Fairly recently, I've written a wrapper for Osu! API v2. In that wrapper, I've written a well-made implementation of both Client Credentials Grant and Authorization Code Grant. I believe it's time for this C# wrapper to support both authorization grants, as many endpoints are unreachable by Client Credentials Grant. If possible, I would like to write the implementation on my fork and create a PR on this repository. 

I humbly request your approval of this operation, minisbett.

Regards,
    Wyvrtn.

Links to associated constructs mentioned, are as listed:

- [OsuApiClient](https://github.com/wyvrtn/osu-java/blob/main/src/main/java/osuapi/client/core/OsuApiClient.java)
- [AbstractApiAuthorization](https://github.com/wyvrtn/osu-java/blob/main/src/main/java/osuapi/client/core/AbstractApiAuthorization.java)
- [AuthorizationCodeGrant](https://github.com/wyvrtn/osu-java/blob/main/src/main/java/osuapi/client/authorization/AuthorizationCodeGrant.java)
- [ClientCredentialsGrant](https://github.com/wyvrtn/osu-java/blob/main/src/main/java/osuapi/client/authorization/ClientCredentialsGrant.java)

**Comment by wyvrtn** [comment]
I've done a framework rehaul of OsuApiClient. This prepares the project to transition into a dual authorization-grant supporting library.

See rehaul [here](https://github.com/wyvrtn/osu-sharp).

**Comment by minisbett** [comment]
I messaged you on Discord!
